#!/bin/sh
OLD_DIR=$(pwd)
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR"

if [ "$SKIP_LOAD" != true ] ; then
    . params.sh.dist
    . tools/getopt.sh
fi

echo "PROJECT=""$PROJECT"
echo "DB_HOST=""$DB_HOST"
echo "DB_USER=""$DB_USER"
echo "DB_PASSWORD=""$DB_PASSWORD"
echo "DB_NAME=""$DB_NAME"
echo "PROJECT_DOMAIN_MASK=""$PROJECT_DOMAIN_MASK"
echo "PROJECT_DOMAIN=""$PROJECT_DOMAIN"
echo "PROTOCOL_SECURED=""$PROTOCOL_SECURED"
echo "USE_REWRITES=""$USE_REWRITES"
echo "ADMIN_USERNAME=""$ADMIN_USERNAME"
echo "ADMIN_PASSWORD=""$ADMIN_PASSWORD"
echo "ADMIN_EMAIL=""$ADMIN_EMAIL"
echo "INSTALL_RUN=""$INSTALL_RUN"
echo "IMPORT_RUN=""$IMPORT_RUN"
echo "SAMPLE_DATA_SQL_RUN=""$SAMPLE_DATA_SQL_RUN"
echo "SAMPLE_DATA_MEDIA_RUN=""$SAMPLE_DATA_MEDIA_RUN"
echo "SAMPLE_DATA_CONFIG_RUN=""$SAMPLE_DATA_CONFIG_RUN"
echo "MYSQL_BIN=""$MYSQL_BIN"
echo "PHP_BIN=""$PHP_BIN"

cd "$OLD_DIR"
